on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      prepo: ${{github.repository}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Minify Actions
      uses: amireshoon/minifyAction@main
      with:
        repo: $prepo
    - name: Minifying Code
      run: |
        minifier.sh $prepo
    - name: Pushing to production branch
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.TOKEN }}
        directory: github/workspace
        branch: production
        message: Minified css, js and html
        author_name: MinifyAction[bot]
        author_email: amireshoon-minifyAction@users.noreply.github.com
        force: true
